name: panther-ros
adopt-info: panther-ros
license: Apache-2.0
summary: The Husarion Panther robot ROS packages
description: |
  ROS packages composing the basic functionalities of the Husarion Panther robot.

grade: devel
confinement: devmode
base: core22

architectures:
  - build-on: arm64

# Later to be parsed from git repo
version: "0.0.1"

package-repositories:
 - type: apt
   ppa: lely/ppa

apps:
  panther-ros:
    command: usr/bin/launcher.sh
    plugs: [network, network-bind, spi, gpio-control, raw-usb, system-observe, can-bus]
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    extensions: [ros2-humble]

parts:
  panther-ros:
    plugin: colcon
    source: https://github.com/husarion/panther_ros.git
    source-branch: ros2-devel
    build-packages:
      - git
      - python3-vcstool
    override-pull: |

      craftctl default

      vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/panther/panther_hardware.repos

      # Ignore so that rosdep doesn't pull deps
      # and colcon doesn't build
      touch $CRAFT_PART_SRC/panther_gazebo/COLCON_IGNORE

    stage-packages: [ros-humble-ros2launch]
    after: [lely]

  # later to be removed probably with package-repositories
  lely:
    plugin: nil
    build-packages:
      - software-properties-common
      - liblely-coapp-dev
      - liblely-co-tools
      - python3-dcf-tools
    stage-packages:
      - liblely-coapp-dev

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
