name: panther-ros
adopt-info: panther-ros
license: Apache-2.0
summary: The Husarion Panther robot ROS packages
description: |
  ROS packages composing the basic functionalities of the Husarion Panther robot.

grade: devel
confinement: devmode
base: core22

architectures:
  - build-on: arm64

# Later to be parsed from git repo
version: "0.0.1"

apps:
  panther-ros:
    command: usr/bin/launcher.sh
    plugs: [network, network-bind, spi, raw-usb, system-observe, can-bus, custom-device, gpiochip]
    environment:
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack"
    extensions: [ros2-humble]

parts:
  panther-ros:
    plugin: colcon
    source: https://github.com/husarion/panther_ros.git
    source-branch: ros2-devel
    build-packages:
      - git
      - build-essential
      - python3-vcstool
    override-pull: |

      craftctl default

      vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/panther/panther_hardware.repos

      # Ignore so that rosdep doesn't pull deps
      # and colcon doesn't build
      touch $CRAFT_PART_SRC/panther_gazebo/COLCON_IGNORE

    stage-packages: [ros-humble-ros2launch]

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      "*.sh": usr/bin/

plugs:
  gpiochip:
    interface: custom-device
    custom-device: gpiochip
